# Generated by Django 5.1.7 on 2025-03-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('did', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('item_category', models.CharField(choices=[('clothing', 'Clothing'), ('toys', 'Toys & Games'), ('books', 'Books & Education'), ('medical', 'Medical Supplies'), ('food', 'Non-perishable Food'), ('other', 'Other')], default='clothing', max_length=50)),
                ('other_category', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('item_description', models.TextField(blank=True)),
                ('item_condition', models.CharField(choices=[('new', 'New'), ('likenew', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=20)),
                ('item_quantity', models.PositiveIntegerField(default=100)),
                ('address_line1', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('pickup_availability', models.CharField(default='yes', max_length=255)),
                ('pickup_notes', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('uploaded_files', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
