# Generated by Django 5.1.7 on 2025-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='did',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
