# Generated by Django 5.1.7 on 2025-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='message',
            new_name='item_description',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='address_line1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('toys', 'Toys & Games'), ('books', 'Books & Education'), ('medical', 'Medical Supplies'), ('food', 'Non-perishable Food'), ('other', 'Other')], default='clothing', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_condition',
            field=models.CharField(choices=[('new', 'New'), ('likenew', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_availability',
            field=models.CharField(default='yes', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='uploaded_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
