# Generated by Django 5.1.7 on 2025-03-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_registration_date_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceNeed',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('pickup_available', models.BooleanField(default=True)),
                ('location', models.TextField()),
                ('contact_number', models.CharField(max_length=13)),
                ('donation_days', models.CharField(max_length=20)),
                ('donation_hours', models.CharField(max_length=20)),
                ('scheduling_notes', models.TextField()),
                ('additional_notes', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_name', to='users.organization')),
            ],
        ),
    ]
