# Generated by Django 5.1.7 on 2025-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
        ('users', '0005_resourceneed'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceneed',
            name='donations',
            field=models.ManyToManyField(blank=True, to='donations.donation'),
        ),
    ]
