# Generated by Django 5.1.7 on 2025-03-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_resourceneed_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourceneed',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourceneed',
            name='resource',
            field=models.ManyToManyField(to='users.resource'),
        ),
    ]
