# Generated by Django 5.1.7 on 2025-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_resource_remove_resourceneed_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceneed',
            name='donation_days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=100),
        ),
    ]
