# Generated by Django 5.1.7 on 2025-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_donationday_alter_resourceneed_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceneed',
            name='donation_days',
        ),
        migrations.AddField(
            model_name='resourceneed',
            name='donation_days',
            field=models.ManyToManyField(blank=True, related_name='donation_day_resource', to='users.donationday'),
        ),
    ]
